### ISSUE TITLE
No Longer Functional: Events Aren't Importing

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/tec-ical-importer#20]
It would seems that this functionality is no longer working. I have the same iCal link I usually pull from for holidays and rotary days configured on https://sandbox.commons.hwdsb.on.ca but the iCal import claims success, but doesn't import any events. 

Perhaps something has changed in the core Event Calendar plugin that's creating a conflict. 

https://outlook.office365.com/owa/calendar/bf003a1abcf84b0aa9e9efc5dbdacc29@hwdsb.on.ca/07bb9e1d6402448e8a681167e17364ed12200477414055768439/calendar.ics

**Comment by r-a-y** [comment]
It seems the issue is with the SG-iCalendar library that we're using. It's quite old and hasn't been updated for a long time.

I'm thinking of switching to this parser: https://github.com/u01jmg3/ics-parser. I've got your sample calendar working locally, but your sample calendar only has one-off events. Do you have a sample iCalendar with a recurring event?

**Comment by mrjarbenne** [comment]
Just added a couple recurring events to that same calendar. 

"No School" should recur every day from Friday to Monday this weekend. It's an All Day Event.

"Enjoy the Weekend" should recur for the next three Saturdays and start at 10AM EST

**Comment by mrjarbenne** [comment]
Updated events cal and events cal pro to the latest version on Prod to allow testing of compatibility.

**Comment by r-a-y** [comment]
I've updated `tec-ical-importer` to use the PHP ICS Parser. We were previously using SG-iCalendar.

I did some local tests and fixed up issues with recurring events. I've added the updated plugin to production. Let me know if you encounter any problems with recurring events.

**Comment by mrjarbenne** [comment]
It's pulling in the single and recurring events 👍. The "Enjoy the Weekend" event is a timed event starting at 10 on the calendar, but it's coming in as a Full Day Event on the Site: 

https://sandbox.commons.hwdsb.on.ca/event/enjoy-the-weekend/2023-04-08/

**Comment by r-a-y** [comment]
> The "Enjoy the Weekend" event is a timed event starting at 10 on the calendar, but it's coming in as a Full Day Event on the Site

Issue is due to how I was checking a Microsoft all day event flag. It was returning a string instead of a boolean. This should be fixed in commit 772b71f.

**Comment by mrjarbenne** [comment]
That did it!
